######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 9 09:26:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += classes.h vars.h \
    mtableview.h
SOURCES += formwin.cpp main.cpp mainwin.cpp wordwin.cpp
RESOURCES += dict4.qrc

FORMS += \
    mainwindow.ui \
    wordwin.ui
